/**
 * WuzlHub API
 * A simple api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export interface Player {
    id?: number;

    roleId?: number;

    firstName?: string;

    lastName?: string;

    userName?: string;

    password?: string;

    email?: string;

    picturePath?: string;

    attendance?: Player.AttendanceEnum;

}
export namespace Player {
    export enum AttendanceEnum {
        Sunday = <any> 'Sunday',
        Saturday = <any> 'Saturday',
        Friday = <any> 'Friday',
        Thursday = <any> 'Thursday',
        Wednesday = <any> 'Wednesday',
        Tuesday = <any> 'Tuesday',
        Monday = <any> 'Monday'
    }
}
