/**
 * WuzlHub API
 * A simple api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class Player {
    id?: number;

    roleId?: number;

    firstName?: string;

    lastName?: string;

    userName?: string;

    password?: string;

    email?: string;

    picturePath?: string;

    attendance?: AttendanceEnum;

}
export enum AttendanceEnum {
    Sunday = 1,
    Saturday = 2,
    Friday = 4,
    Thursday = 8,
    Wednesday = 16,
    Tuesday = 32,
    Monday = 64
}
export namespace PlayerNamespace {
}
