/**
 * WuzlHub API
 * A simple api
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

import * as models from './models';

export class TeamDto {
    team?: models.Team;

    id?: number;

    player1?: models.PlayerDto;

    player2?: models.PlayerDto;

}
